apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: fastapi-project
  labels:
    app: crud-app
spec:
  selector:
    app: crud-app
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
